import { z } from "zod";

export const receiptEntryLineSchema = z.object({
  lineId: z.string().optional(),
  productId: z.string().nullable().optional(),
  productName: z.string(),
  description: z.string().nullable().optional(),
  colour: z.string().nullable().optional(),
  hsnCode: z.string().nullable().optional(),
  poNo: z.string().nullable().optional(),
  dcNo: z.string().nullable().optional(),
  size: z.string().nullable().optional(),
  unit: z.string().nullable().optional(),
  quantity: z.coerce.number(),
  rate: z.coerce.number(),
  discountAmount: z.coerce.number(),
  taxRate: z.coerce.number(),
  taxAmount: z.coerce.number().optional(),
  lineTotal: z.coerce.number().optional(),
});

export const receiptAllocationSchema = z.object({
  allocationId: z.string().optional(),
  documentType: z.string(),
  documentId: z.string().nullable().optional(),
  documentNo: z.string(),
  documentDate: z.string().nullable().optional(),
  documentTotal: z.coerce.number(),
  previousBalance: z.coerce.number(),
  allocatedAmount: z.coerce.number(),
  balanceAfterAllocation: z.coerce.number().optional(),
});

export const receiptEntrySchema = z.object({
  entryId: z.string(),
  entryType: z.literal("receipt"),
  documentNo: z.string(),
  documentDate: z.string(),
  partyId: z.string().nullable().optional(),
  partyName: z.string(),
  partyType: z.string().nullable().optional(),
  partyGstin: z.string().nullable().optional(),
  partyStateCode: z.string().nullable().optional(),
  partyStateName: z.string().nullable().optional(),
  supplierBillNo: z.string().nullable().optional(),
  supplierBillDate: z.string().nullable().optional(),
  billingAddress: z.string().nullable().optional(),
  shippingAddress: z.string().nullable().optional(),
  placeOfSupply: z.string().nullable().optional(),
  referenceNo: z.string().nullable().optional(),
  referenceDate: z.string().nullable().optional(),
  dueDate: z.string().nullable().optional(),
  ledgerName: z.string().nullable().optional(),
  paymentMode: z.string().nullable().optional(),
  subtotal: z.coerce.number(),
  discountTotal: z.coerce.number(),
  taxableTotal: z.coerce.number(),
  taxTotal: z.coerce.number(),
  roundOff: z.coerce.number(),
  grandTotal: z.coerce.number(),
  paidAmount: z.coerce.number(),
  balanceAmount: z.coerce.number(),
  amount: z.coerce.number(),
  tdsAmount: z.coerce.number(),
  netAmount: z.coerce.number(),
  allocatedAmount: z.coerce.number(),
  unallocatedAmount: z.coerce.number(),
  status: z.string(),
  paymentStatus: z.string(),
  notes: z.string().nullable().optional(),
  terms: z.string().nullable().optional(),
  irn: z.string().nullable().optional(),
  ackNo: z.string().nullable().optional(),
  ackDate: z.string().nullable().optional(),
  signedQr: z.string().nullable().optional(),
  ewayBillNo: z.string().nullable().optional(),
  ewayBillDate: z.string().nullable().optional(),
  transportName: z.string().nullable().optional(),
  vehicleNo: z.string().nullable().optional(),
  ewayPart: z.string().nullable().optional(),
  source: z.record(z.string(), z.unknown()).nullable().optional(),
  isActive: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
  lines: z.array(receiptEntryLineSchema),
  allocations: z.array(receiptAllocationSchema).default([]),
  comments: z.array(z.object({ authorEmail: z.string(), body: z.string(), createdAt: z.string() })).default([]),
  activities: z.array(z.object({ activityType: z.string(), actorEmail: z.string(), message: z.string(), createdAt: z.string() })).default([]),
}).passthrough();

export const receiptEntriesSchema = z.array(receiptEntrySchema);